using SwarmECS.FixedPoint;

namespace SwarmECS.Simulation.Netcode
{

/// <summary>
/// GGPO-style state restore and deterministic replay over a fixed command timeline.
/// </summary>
public sealed class RollbackController
{
    private readonly SwarmWorld _world;
    private readonly IDeterministicSimulation _simulation;
    private readonly CommandTimeline _commands;
    private readonly WorldSnapshotRing _snapshots;
    private int _nextSequence;

    public RollbackController(
        SwarmWorld world,
        IDeterministicSimulation simulation,
        int historyLength = 64,
        int commandCapacity = 512)
    {
        _world = world;
        _simulation = simulation;
        _commands = new CommandTimeline(commandCapacity);
        _snapshots = new WorldSnapshotRing(world.Config.Capacity, historyLength);
        _snapshots.Save(world);
    }

    public int RollbackCount { get; private set; }

    public int LastResimulatedTicks { get; private set; }

    public int TotalResimulatedTicks { get; private set; }

    public int HistoryLength => _snapshots.HistoryLength;

    public int CommandCount => _commands.Count;

    /// <summary>
    /// Next sequence reserved for commands generated by this local demo controller.
    /// Network commands must carry the authority-provided sequence instead.
    /// </summary>
    public int NextLocallyGeneratedSequence => _nextSequence;

    public ulong LastHashBeforeRollback { get; private set; }

    public ulong LastHashAfterRollback { get; private set; }

    public void Step()
    {
        _snapshots.Save(_world);

        // Saving tick T overwrites the T-HistoryLength slot. The oldest tick
        // that can still be restored is therefore T-HistoryLength+1. Commands
        // on that boundary must remain available for a late rollback replay.
        long oldestRestorableTick = (long)_world.Tick - HistoryLength + 1L;
        _commands.DiscardBeforeTick(
            oldestRestorableTick > 0L ? (int)oldestRestorableTick : 0);

        _commands.ApplyAtTick(_world, _world.Tick);
        _simulation.Step(_world);
        _world.AdvanceTick();
    }

    public bool QueueCommand(SimulationCommand command)
    {
        if (!IsValidCommand(command) || command.Tick < _world.Tick)
        {
            return false;
        }

        if (!_commands.Add(command))
        {
            return false;
        }

        AdvanceLocalSequencePast(command.Sequence);
        return true;
    }

    public bool QueueSpatialIndexMode(SpatialIndexMode mode)
    {
        if ((uint)mode > (uint)SpatialIndexMode.KdTreeKNearest)
        {
            return false;
        }

        SimulationCommand command = new(
            _world.Tick,
            _nextSequence,
            SimulationCommandType.SetSpatialIndexMode,
            (byte)mode,
            FPVector2.Zero);
        return QueueCommand(command);
    }

    /// <summary>
    /// Injects a complete authority-provided command from an already simulated tick.
    /// Tick and Sequence are preserved exactly; callers must not reconstruct them on arrival.
    /// </summary>
    public bool InjectLateCommand(SimulationCommand command)
    {
        if (!IsValidCommand(command))
        {
            return false;
        }

        int currentTick = _world.Tick;
        if (command.Tick >= currentTick)
        {
            return false;
        }

        if (!_snapshots.Contains(_world, command.Tick))
        {
            return false;
        }

        if (!_commands.Add(command))
        {
            return false;
        }

        AdvanceLocalSequencePast(command.Sequence);

        LastHashBeforeRollback = _world.ComputeStateHash();
        if (!_snapshots.TryRestore(_world, command.Tick))
        {
            return false;
        }

        int replayed = 0;
        while (_world.Tick < currentTick)
        {
            Step();
            replayed++;
        }

        LastResimulatedTicks = replayed;
        TotalResimulatedTicks += replayed;
        RollbackCount++;
        LastHashAfterRollback = _world.ComputeStateHash();
        return true;
    }

    /// <summary>
    /// Local Host-only latency demo. It fabricates a command from the local sequence counter;
    /// real network delivery must call InjectLateCommand with the full authoritative command.
    /// </summary>
    public bool InjectLocallyGeneratedLateGroupTarget(int latencyTicks, int group, FPVector2 target)
    {
        if ((uint)group >= SwarmWorld.GroupCount || HistoryLength < 2)
        {
            return false;
        }

        int clampedLatency = latencyTicks < 1 ? 1 : latencyTicks;
        if (clampedLatency >= HistoryLength)
        {
            clampedLatency = HistoryLength - 1;
        }

        int originTick = _world.Tick - clampedLatency;
        if (originTick < 0)
        {
            return false;
        }

        return InjectLateCommand(new SimulationCommand(
            originTick,
            _nextSequence,
            SimulationCommandType.SetGroupTarget,
            (byte)group,
            target));
    }

    public void ResetHistory()
    {
        _commands.Clear();
        _snapshots.Clear();
        _snapshots.Save(_world);
        _nextSequence = 0;
        RollbackCount = 0;
        LastResimulatedTicks = 0;
        TotalResimulatedTicks = 0;
        LastHashBeforeRollback = 0;
        LastHashAfterRollback = 0;
    }

    private static bool IsValidCommand(SimulationCommand command)
    {
        if (command.Tick < 0 || command.Sequence < 0)
        {
            return false;
        }

        return command.Type switch
        {
            SimulationCommandType.SetGroupTarget => command.Group < SwarmWorld.GroupCount,
            SimulationCommandType.SetSpatialIndexMode =>
                command.Group <= (byte)SpatialIndexMode.KdTreeKNearest,
            _ => false,
        };
    }

    private void AdvanceLocalSequencePast(int sequence)
    {
        if (sequence >= _nextSequence)
        {
            _nextSequence = sequence == int.MaxValue ? 0 : sequence + 1;
        }
    }
}
}
